source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'NumberFacts' do
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftLint'

  target 'NumberFactsTests' do
    inherit! :search_paths
    pod 'Alamofire', '~> 4.5'
    pod 'SwiftLint'
  end

end
