source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'NumberFacts' do
  use_frameworks!
  pod 'Alamofire', '~> 4.5'

  target 'NumberFactsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end